### ISSUE TITLE
Expand elements covered by EML's attribute* index fields beyond just dataTable

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/d1_cn_index_processor#2]
We noticed today that our EML index processing rules in [`application-context-eml-base.xml`](https://github.com/DataONEorg/d1_cn_index_processor/blob/main/src/main/resources/application-context-eml-base.xml#L457) only capture `attribute` elements under a `dataTable` element (e.g., `//dataTable/attributeList/attribute`). However, EML supports attributes under all entity types, not just `dataTable`. This is probably confusing to users and something I think we should address.

I suggest we change the relevant XPath selectors in `application-context-eml-base.xml` to cover all entity types. I can't think of any downsides to the change, other than having to reindex content. I think all users will want to be able to search for attributes on other entity types.

@datadavev @csjx: Can I get a +1 from you? @mbjones already put in a vote for this change in our salmantics call for this change.

**Comment by csjx** [comment]
Yes, I think that was just an oversight by Skye, he was not super familiar with all of EML. Sounds good +1.

**Comment by amoeba** [comment]
Thanks @csjx. I'll take that as enough evidence to move forward with the change. @taojing2002, any chance you have some spare cycles to take a look at this in the next release of this package? Also https://github.com/NCEAS/metacat/issues/1468.

**Comment by taojing2002** [comment]
close this issue. 
See https://github.com/NCEAS/metacat/issues/1361
