### ISSUE TITLE
Add `schema.org/Dataset` `distribution` info as serviceEndpoint in index

### ISSUE THREAD

**Issue by datadavev** [DataONEorg/d1_cn_index_processor#23]
Amend the [indexer rule for populating `serviceEndpoint`](https://github.com/DataONEorg/d1_cn_index_processor/blob/1940a444c2338ecc08c9622e84436084451d3651/src/main/resources/application-context-schema-org.xml#L772) to add an entry for the `contentUrl` if present in a `distribution` entry of type `DataDownload` in `schema.org/Dataset` JSON-LD metadata.

For example: 
```json
    distribution: {
      "@type": "DataDownload",
      "contentUrl": "http://datadryad.org/api/v2/datasets/doi%253A10.5061%252Fdryad.5qb78/download",
      "encodingFormat": "application/zip"
    },
```
(from https://so.test.dataone.org/mnTestDRYAD/v2/object/sha256:a90d598d491ecc47051387ff5bd58042dff128064ef74358c7e3318bdf3a25fe )

The URL `http://datadryad.org/api/v2/datasets/doi%253A10.5061%252Fdryad.5qb78/download` should be added to the list of values for `serviceEndpoint`.

**Comment by gothub** [comment]
The query that populates `serviceEndpoint` has been updated as described above.
