### ISSUE TITLE
Add formatId for JSON-LD documents

### ISSUE THREAD

**Issue by gothub** [DataONEorg/d1_cn_index_processor#4]
In order to index SO:Dataset documents, a formatId for these documents needs to be added.
The Media Type for JSON-LD documents is[ *application/ld+json*](https://www.iana.org/assignments/media-types/application/ld+json)

related issue: https://github.com/DataONEorg/d1_cn_index_processor/issues/3

**Comment by gothub** [comment]
formatId entries are now added via the formats repo: https://github.com/DataONEorg/object-formats, so create a pull request (or issue?) in that repo for this.

**Comment by datadavev** [comment]
See DataONEorg/object-formats#21

**Comment by gothub** [comment]
Duplicate of https://github.com/DataONEorg/object-formats/issues/21
