### ISSUE TITLE
Create SO:Dataset to DataONE solr crosswalk

### ISSUE THREAD

**Issue by gothub** [DataONEorg/d1_cn_index_processor#5]
Create the mapping from schema.org *Dataset* descriptions to the DataONE Solr index. 
This mapping will first be documented in this repo, for development usage, and then added to the DataONE API documentation (i.e. https://github.com/DataONEorg/api-documentation/tree/master/source/design) so that users understand how *SO:Dataset* descriptions are indexed.

TODO:
- [x] create table of the mapping
- [x] develop SPARQL queries to extract data from JSON-LD documents (converted to RDF)
- [x] update DataONE API documentation when the mapping is fully documented and released

**Comment by gothub** [comment]
@mbjones regarding the DataONE API documentation detailing the SO:Dataset indexing, I followed the example of current documentation such as https://releases.dataone.org/online/api-documentation-v2.0/design/SearchMetadata_eml.html, which shows XPaths and references to the KNB EML documentation. 
- For the 'Path' column, for SO:Dataset, instead of XPaths I put SPARQL queries that were used to extract properties from the JSON-LD documents. While most readers won't require this level of technical detail, it does accurately show how the info is extracted.
- also for the 'Reference' column I referred to the appropriate section in the ESIP SOSO guide, instead of referring to https://schema.org, which doesn't provide context for the fields used, i.e. for Solr `author`, the property extracted is `https://schema.org/name`, but in the context of SO:Dataset > SO:creator

Is this approach to documenting the SO:Dataset indexing valid, or should a different one be used?

**Comment by mbjones** [comment]
Sounds like a good approach to me @gothub . Several groups have asked for our crosswalks recently, so that is good to keep documented. I have also pointed them at the config files for the indexer which actually has all of the crosswalks, whereas in sphinx I think we are missing some. But this sounds good.

Where can I see this document? Did you add it to https://github.com/DataONEorg/api-documentation?

**Comment by gothub** [comment]
The document will be added to that repo this morning, when I've successfully built the documentation locally. It's almost ready, I just have to finish configuring the python tools required for the doc build.

**Comment by gothub** [comment]
This issue has been superseded by https://github.com/DataONEorg/api-documentation/issues/14
